"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var practicaUno_1 = require("./practicaUno");
var gatoUno = new practicaUno_1.Gato("Oscar", "Masculino", 5, 10, "Naranja", "Suave");
console.log("Prueba de que se le dió nombre");
console.log(gatoUno.name);
console.log("Prueba de que se cambió nombre");
gatoUno.setName = "Oscarin";
console.log(gatoUno.getName);
console.log("Prueba de toString");
console.log(gatoUno.toString());
